##### Pipeline

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  rg_group: 'azure-tf-scaleset'
  sa_name: 'iaaclabs'
  cont_name: 'iaacazuretfscaleset'
  storage_key: 'terraform.tfstate'

stages:
  - stage: tfvalidate
    jobs:
      - job: validate
        continueOnError: false
        steps:
