###  Test Pipeline

 trigger:
 - none
 
 pool:
   vmImage: 'ubuntu-latest'

 steps:

  - task: TerraformInstaller@0
    inputs:
      terraformVersion: 'latest'

  - task: TerraformTaskV3@3
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.ArtifactsDirectory)'
      backendServiceArm: 'Pay-As-You-Go(a6f24a81-7804-44a9-b074-25a9781afd24)'
      backendAzureRmResourceGroupName: 'FRED'
      backendAzureRmStorageAccountName: 'iaaclabs'
      backendAzureRmContainerName: 'iaacazuretfscaleset'
      backendAzureRmKey: 'terraform.tfstate'

  - task: TerraformTaskV3@3
    inputs:
      provider: 'azurerm'
      command: 'validate'
      workingDirectory: '$(System.ArtifactsDirectory)'

  - task: TerraformTaskV3@3
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.ArtifactsDirectory)'
      environmentServiceNameAzureRM: 'Pay-As-You-Go(a6f24a81-7804-44a9-b074-25a9781afd24)'